project: comparing_models
entity: deya-03-the-university-of-manchester
program: /share/nas2_3/adey/full_models/main.py

metric:
  name: train/total_loss_per_100
  goal: minimize

method: grid
parameters:
  architecture:
    values: ["AE"]
  latent_dim:
    values: [64] 
  num_hiddens:
    values: [256]
  num_residual_layers:
    values: [2]
  num_residual_hiddens:
    values: [32]
  learning_rate:
    values: [0.0002]
  batch_size:
    values: [4]  
  save_latents:
    values: [True]  

max_runs: 50  
