project: comparing_models
entity: deya-03-the-university-of-manchester
program: /share/nas2_3/adey/astro/clean_code/train_ae.py

metric:
  name: train/total_loss_per_100
  goal: minimize

method: grid
parameters:
  latent_dim:
    values: [32, 64, 128]  
  num_hiddens:
    values: [128, 256]
  num_residual_layers:
    values: [2, 3]
  num_residual_hiddens:
    values: [32, 64]
  learning_rate:
    values: [0.0001, 0.0002, 0.0005]
  batch_size:
    values: [4, 8]  
  save_latents:
    values: [True]  

max_runs: 50  

parameter_constraints:
  - "(latent_dim * log2(latent_dim)) <= 3072"
``
