wandb_version: 1

architecture:
  desc: null
  value: AE
batch_size:
  desc: null
  value: 4
image_size:
  desc: null
  value: 150
num_training_updates:
  desc: null
  value: 20000
learning_rate:
  desc: null
  value: 0.0002
commitment_cost:
  desc: null
  value: 0.25
num_embeddings:
  desc: null
  value: 256
embedding_dim:
  desc: null
  value: 64
latent_dim:
  desc: null
  value: 64
num_hiddens:
  desc: null
  value: 256
num_residual_layers:
  desc: null
  value: 2
num_residual_hiddens:
  desc: null
  value: 32
dataset_path:
  desc: null
  value: /share/nas2_3/adey/data/galaxy_zoo/
num_workers:
  desc: null
  value: 1
wandb_project:
  desc: null
  value: comparing_models
wandb_entity:
  desc: null
  value: your-wandb-entity-or-username
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.18.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1738852269
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 5
      - 41
      - 51
      - 53
      - 55
      3:
      - 16
      - 23
      - 37
      - 61
      4: 3.9.6
      5: 0.18.5
      8:
      - 5
      13: linux-x86_64
save_latents:
  desc: null
  value: true
